<Project>
  <PropertyGroup>
    <!-- MAUI Version -->
    <MauiVersion>9.0.9</MauiVersion>
    
    <!-- NuGet -->
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    
    <!-- Warnings -->
    <WarningLevel>9999</WarningLevel>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    
    <!-- Code Analysis -->
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>
